project_id = "rnrsfzgmgjdzufqrsnhd"

[functions.generate-rss]
verify_jwt = false

[functions.generate-book-cover]
verify_jwt = false

[functions.create-cover-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
